ISLP Chapter 2.3 - Introduction to python

In [1]:
import numpy as np
import pandas as pd
import matplotlib

Numpy Functions

In [2]:
#creating arrays (vectors)
x = np.array([3,4,5])
y = np.array([4,9,7])

In [3]:
x + y

array([ 7, 13, 12])

In [4]:
#create array (matrix)
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [5]:
#show dimensions of the array
x.ndim

2

In [6]:
#show type of variables in it
x.dtype

dtype('int32')

In [7]:
#matrix shape
x.shape

(2, 2)

In [8]:
#sum values inside of array
x = np.array([1,2,3,4])
x.sum() # can also use np.sum(x)

10

In [9]:
# we can turn a vecotr into a matrix with reshape()
x = np.array([1,2,3,4,5,6])
print('original x \n', x)
x_reshape = x.reshape((2,3))
print('after reshape \n' , x_reshape)

original x 
 [1 2 3 4 5 6]
after reshape 
 [[1 2 3]
 [4 5 6]]


In [10]:
#accesing elemnts in an array, remember python counts from 0
print(x_reshape[0,0])
print(x_reshape[1,2])
print(x[5])

1
6
6


In [11]:
x_reshape[1,2]

6

In [12]:
#x and its reshape are linked, change one and you change both
print('x before we modify x_reshape \n', x)
print('x_reshape before we modify x_reshape \n', x_reshape)
x_reshape[0,0] = 5
print('x_reshape after we modify first element \n', x_reshape)
print('x aftere we modify x_reshape \n', x)


x before we modify x_reshape 
 [1 2 3 4 5 6]
x_reshape before we modify x_reshape 
 [[1 2 3]
 [4 5 6]]
x_reshape after we modify first element 
 [[5 2 3]
 [4 5 6]]
x aftere we modify x_reshape 
 [5 2 3 4 5 6]


In [13]:
#some atributes - shape, number of dimension , and transpose
x_reshape.shape, x_reshape.ndim, x_reshape.T

((2, 3),
 2,
 array([[5, 4],
        [2, 5],
        [3, 6]]))

In [14]:
#some functions
np.sqrt(x), x**0.5 , x**2

(array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
        2.44948974]),
 array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
        2.44948974]),
 array([25,  4,  9, 16, 25, 36]))

In [15]:
#generating normaly distributed values , default is N(0,1) - np.random.normal(loc=0, scale = 1, size = 1)
x = np.random.normal(size = 50)
x

array([-0.91243483, -0.6200402 ,  1.88876477,  0.73239581,  0.49260427,
       -0.21554412, -0.65520007, -0.58360002, -0.67064086, -0.70663215,
       -0.23842224,  1.30122919, -0.68936532,  0.50831479,  1.80142735,
       -0.37621224,  1.31438719,  1.09658992, -1.11784151, -0.16838413,
       -1.21231255,  1.32633314, -1.8454316 ,  0.61826484, -0.69622274,
       -0.46055483,  0.6063124 ,  1.94169641,  1.19510995, -0.07870417,
       -1.94289092,  0.28988567, -1.36905257,  1.00343438, -0.89939599,
        0.91792411, -2.03570765, -1.05301073,  1.29383598,  0.16076543,
        0.64458103,  0.85805445,  0.66881265, -0.45395056,  2.23350851,
        0.3665143 ,  0.76600568, -0.24556321, -0.08540149,  0.46626016])

In [16]:
#We can also add random ammounts to each element
y = x + np.random.normal(loc = 50, scale = 1 , size = 50)

In [17]:
#Numpy has a matrix correlation function
np.corrcoef(x,y)

array([[1.        , 0.72854386],
       [0.72854386, 1.        ]])

In [18]:
#to maintain consistency when reruning the program we can set a seed for the random generator
rng = np.random.default_rng(1303)
print(rng.normal(scale = 5 , size = 2))
rng2 = np.random.default_rng(1303)
print(rng2.normal(scale = 5, size = 2))

[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]


In [19]:
# we can use the folowing to obtain the mean, variance and standard deviation of an array
np.mean(y), np.var(y), np.std(y)

(50.22993128448904, 2.091310044661633, 1.446136246921995)

In [20]:
#We can also apply it to the rows or columns individually with axis
X = rng.standard_normal((10,3))
print(X)
print(' mean by column is' , X.mean(axis=0))
print(' mean by row is' , X.mean(axis=1))

[[-2.03072919  0.22681229 -0.82806113]
 [-0.94971965  0.09748025  1.13071035]
 [-0.503177   -1.6146684  -0.51143783]
 [ 1.30857567 -0.60106271 -1.04358358]
 [-0.77787108 -0.03621124 -2.366124  ]
 [-0.12532525 -1.04473968 -0.46412883]
 [ 0.33555586 -0.11933931 -0.19707608]
 [-0.35307465  0.09562671  0.83201011]
 [ 1.78919398 -3.25891725  1.06043415]
 [-0.69168156 -1.16488556  0.99099849]]
 mean by column is [-0.19982529 -0.74199049 -0.13962583]
 mean by row is [-0.87732601  0.09282365 -0.87642774 -0.11202354 -1.06006877 -0.54473125
  0.00638016  0.19152072 -0.13642971 -0.28852288]


In [21]:
# we can also get the mean as
X.mean(0)

array([-0.19982529, -0.74199049, -0.13962583])

Sequences and SLice Notation

In [22]:
# we can use np.linspace() to create a sequence
seq1 = np.linspace(0,10,11)
seq1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
#np.arange(a, b, step = 1) is similar but returns a sequence spaced out by a 'step', default is 1
seq2 = np.arange(0,10)
seq2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Notice that 10 is not in seq2, due to how slicing works in python

In [29]:
#we can slice our data using indexing notation [:]
"hello world"[3:6] #[3:6] is shothand for slice(3,6)

'lo '

In [30]:
"hello world"[slice(3,6)] #this still doenst include the 7th character

'lo '

Indexing data

In [31]:
A = np.array(np.arange(16)).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
A[1,2] #second row, third column, count from 0

6

In [35]:
#we can also index with a list
A[[1,3]] #second and fourth row

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [36]:
#to index columns we need to skip the first argument with :
A[:,[0,2]]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

In [37]:
#it can get tricky tho, indexing like this doesnt allow us to extract specific columns and rows
A[[1,3],[0,2]]

array([ 4, 14])

In [38]:
# to reach our goal  (second and fourth row and first and third column), we cna do it in 'steps'
A[[1,3]][:,[0,2]] # first index the rows and then index the result to get the columns of those

array([[ 4,  6],
       [12, 14]])

In [39]:
#np.ix_() helps extract a submatrix using lists wich can be more convenient
idx = np.ix_([1,3],[0,2,3])
A[idx]

array([[ 4,  6,  7],
       [12, 14, 15]])

In [40]:
#alternatively we can use slices
A[1:4:2,0:3:2]

array([[ 4,  6],
       [12, 14]])